version: '3.4'

services:
  in.api:
    image: ei8works/tag.in.api:0.1.0
    build:
      context: .
      dockerfile: main\Port.Adapter\In\Api\Dockerfile
  out.api:
    image: ei8works/tag.out.api:0.1.0
    build:
      context: .
      dockerfile: main\Port.Adapter\Out\Api\Dockerfile